version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    env_file:
      - ./apps/api/.env
    volumes:
      - .:/app
      - /app/node_modules
      - /app/apps/api/node_modules
    environment:
      - DB_HOST=host.docker.internal
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "5000:5000"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  web:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    volumes:
      - .:/app:delegated
      - /app/node_modules
      - /app/apps/web/node_modules
    ports:
      - "3000:3000"
    environment:
      - API_URL=http://api:5000
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:5000
      - WATCHPACK_POLLING=true
    command: npm run dev -w apps/web -- -H 0.0.0.0 --webpack
    stdin_open: true
    tty: true
    depends_on:
      - api
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"